name: speakcheesy_app
description: "Mobile application for Bert's SpeakCheezy food truck and restaurant."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  phosphor_flutter: ^2.1.0
  google_nav_bar: ^5.0.6
  popover: ^0.3.0+1
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.9.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
